# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.cache/wt [current_project]
set_property parent.project_path C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/new/ASU.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/Project/BitShifterLeft/BitShifterLeft.srcs/sources_1/new/BitShifterLeft.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/Project/BitShifterRight/BitShifterRight.srcs/sources_1/new/BitShifterRight.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/Project/BitwiseAND/BitwiseAND.srcs/sources_1/new/BitwiseAND.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/Project/BitwiseNOT/BitwiseNOT.srcs/sources_1/new/BitwiseNOT.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/Project/BitwiseOR/BitwiseOR.srcs/sources_1/new/BitwiseOR.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/Project/BitwiseXOR/BitwiseXOR.srcs/sources_1/new/BitwiseXOR.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/new/Comparator_4bit.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/sources_1/imports/new/D_FF.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/new/Decoder_4_16.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedRegisterBank/ImprovedRegisterBank.srcs/sources_1/new/Decoder_4_16.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/sources_1/imports/new/FA.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/sources_1/imports/new/HA.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/sources_1/new/Improved4BitAdder.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/new/ImprovedInstructionDecoder.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/sources_1/new/ImprovedPC.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/new/ImprovedProgramROM.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/new/ImprovedRegisterBank.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/new/LUT_16_7.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/new/Multiplier_4.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/new/NineWay4BitMUX.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/new/OperationSelector.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/sources_1/imports/new/RCA_4.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/sources_1/new/Reg.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/new/SixteenWay4BitMUX.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/new/Slow_Clk.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/imports/new/TwoWay4Bit_Mux.vhd
  C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/sources_1/new/ImprovedNanoprocessor.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/constrs_1/new/InprovedNanoCons.xdc
set_property used_in_implementation false [get_files C:/Users/dinur/ProjectImproved/Project/ImprovedNanoprocessor/ImprovedNanoprocessor.srcs/constrs_1/new/InprovedNanoCons.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top ImprovedNanoprocessor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ImprovedNanoprocessor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ImprovedNanoprocessor_utilization_synth.rpt -pb ImprovedNanoprocessor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
